### ISSUE TITLE
Fix Cython coverage

### ISSUE THREAD

**Issue by jakirkham** [jakirkham/cyminmax#13]
Measuring and reporting the coverage of the Cython module does not appear to be working correctly. In particular, an error is seen when reporting the coverage and trying to submit it. This occurs on both Python 2 and Python 3. Details from the report and submission failures are included below. Links to relevant CI logs are included in the details. While the errors may initially appear to be unrelated, both issues share the same cause on local inspection. On the surface, the problem seems to share a similar cause to issue ( https://github.com/cython/cython/issues/1898 ). However this is not limited to Windows and upgrading `cython` to `0.27.1+` does not seem to affect the issue.

<details>
<summary>Coverage Report Error:</summary>

```python
$ coverage report -m
src/cyminmax.pyx   TypeError: 'NoneType' object is not iterable
Name       Stmts   Miss Branch BrPart  Cover   Missing
------------------------------------------------------
setup.py      54      0     11      0   100%
```

xref: https://travis-ci.org/jakirkham/cyminmax/jobs/298596443#L883-L887

</details>

<br>

<details>
<summary>Coveralls Submission Error:</summary>

```python
$ coveralls
...
Traceback (most recent call last):
  File "/home/travis/miniconda/envs/dplenv/bin/coveralls", line 6, in <module>
    sys.exit(coveralls.wear())
  File "/home/travis/miniconda/envs/dplenv/lib/python3.5/site-packages/coveralls/__init__.py", line 94, in wear
    source_files=coverage.coveralls(args.base_dir, ignore_errors=args.ignore_errors, merge_file=args.merge_file),
  File "/home/travis/miniconda/envs/dplenv/lib/python3.5/site-packages/coveralls/control.py", line 9, in coveralls
    return reporter.report(base_dir, ignore_errors=ignore_errors, merge_file=merge_file)
  File "/home/travis/miniconda/envs/dplenv/lib/python3.5/site-packages/coveralls/report.py", line 20, in report
    analysis = self.coverage._analyze(fr)
  File "/home/travis/miniconda/envs/dplenv/lib/python3.5/site-packages/coverage/control.py", line 891, in _analyze
    return Analysis(self.data, it)
  File "/home/travis/miniconda/envs/dplenv/lib/python3.5/site-packages/coverage/results.py", line 19, in __init__
    self.statements = self.file_reporter.lines()
  File "/home/travis/miniconda/envs/dplenv/lib/python3.5/site-packages/Cython/Coverage.py", line 276, in lines
    return set(self._code)
TypeError: 'NoneType' object is not iterable
```

xref: https://travis-ci.org/jakirkham/cyminmax/jobs/298596443#L1003-L1018

</details>

**Comment by jakirkham** [comment]
Should add that Coveralls submissions are broken until this is addressed.

**Comment by jakirkham** [comment]
Raised upstream as issue ( https://github.com/cython/cython/issues/1985 ).
