### ISSUE TITLE
Enable coverage in tests and CI again

### ISSUE THREAD

**Issue by jakirkham** [jakirkham/cyminmax#9]
Am running into some painful issues with coverage and Cython on a trivial module. Have no idea what is causing them as there really isn't any code to speak of. To make matters worse am seeing different results locally and on CI. So there is something I'm missing when trying to reproduce these issues.

Details are shown below. One looks like a solved issue in Cython, but upgrading doesn't fix it. Same story when using the latest `coverage`. Plus the issue mentions problems on Windows, but we are seeing these failures on macOS and Linux. Have also experimented with different strategies like `cythonize` to no avail.

<details>
<summary>CI</summary>

```
Name       Stmts   Miss Branch BrPart  Cover   Missing
------------------------------------------------------
setup.py   IndexError: pop from empty list
```

</details>

<br>

<details>
<summary>Local</summary>

```
Name               Stmts   Miss Branch BrPart  Cover
----------------------------------------------------
setup.py   IndexError: pop from empty list
src/cyminmax.pyx   TypeError: 'NoneType' object is not iterable
No data to report.
```

</details>

<br>

ref: https://travis-ci.org/jakirkham/cyminmax/jobs/298224791#L890
xref: https://github.com/cython/cython/issues/1898
xref: https://github.com/jakirkham/cyminmax/pull/4

**Comment by jakirkham** [comment]
We should try to come up with a simple reproducer and send it upstream.

**Comment by jakirkham** [comment]
Was able to reproduce the issue on CI finally. After forcing a `raise` into `coverage` version `4.0.3`'s `coverage.summary` on line `104`. This gives us a traceback that looks something like this. So this appears to be a pure `coverage` error and not `cython` related unlike the local issue that we reproduced.

<details>

```python
Traceback (most recent call last):
  File "/zopt/conda2/envs/cython/bin/coverage", line 6, in <module>
    sys.exit(coverage.cmdline.main())
  File "/zopt/conda2/envs/cython/lib/python3.6/site-packages/coverage/cmdline.py", line 741, in main
    status = CoverageScript().command_line(argv)
  File "/zopt/conda2/envs/cython/lib/python3.6/site-packages/coverage/cmdline.py", line 504, in command_line
    skip_covered=options.skip_covered, **report_args)
  File "/zopt/conda2/envs/cython/lib/python3.6/site-packages/coverage/control.py", line 966, in report
    return reporter.report(morfs, outfile=file)
  File "/zopt/conda2/envs/cython/lib/python3.6/site-packages/coverage/summary.py", line 68, in report
    analysis = self.coverage._analyze(fr)
  File "/zopt/conda2/envs/cython/lib/python3.6/site-packages/coverage/control.py", line 891, in _analyze
    return Analysis(self.data, it)
  File "/zopt/conda2/envs/cython/lib/python3.6/site-packages/coverage/results.py", line 28, in __init__
    self._arc_possibilities = sorted(self.file_reporter.arcs())
  File "/zopt/conda2/envs/cython/lib/python3.6/site-packages/coverage/python.py", line 165, in arcs
    return self.parser.arcs()
  File "/zopt/conda2/envs/cython/lib/python3.6/site-packages/coverage/parser.py", line 238, in arcs
    for l1, l2 in self.byte_parser._all_arcs():
  File "/zopt/conda2/envs/cython/lib/python3.6/site-packages/coverage/parser.py", line 624, in _all_arcs
    arcs.update(bp._arcs())
  File "/zopt/conda2/envs/cython/lib/python3.6/site-packages/coverage/parser.py", line 561, in _arcs
    chunks = self._split_into_chunks()
  File "/zopt/conda2/envs/cython/lib/python3.6/site-packages/coverage/parser.py", line 493, in _split_into_chunks
    block_stack.pop()
IndexError: pop from empty list
```

</details>

<br>

Looks like this is issue ( https://bitbucket.org/ned/coveragepy/issues/434 ). Upgrading to `coverage` version `4.1` fixes the issue. Might need to do a one off Python 3.4 release in conda-forge to get something that will work. ( https://github.com/conda-forge/coverage-feedstock/pull/27 )

**Comment by jakirkham** [comment]
Now able to reproduce the local issue on CI. Seems the issue was caused by a `pip install -e .` that proceeded the tests. This triggered a build of the Cython library. However when the tests were run the library was not rebuilt. Meaning the library did not have any Cython directives or C macros set that would allow for coverage testing. Dropping the `pip install -e .` ensured the build occurred during testing and so had the right Cython directives and C macros set.

ref: https://travis-ci.org/jakirkham/cyminmax/jobs/298307799

**Comment by jakirkham** [comment]
Looks like updating to `coverage` version `4.4.2` in PR ( https://github.com/jakirkham/cyminmax/pull/11 ) resolves the failure with `setup.py`. The Cython coverage issue is still outstanding, but will open that as a new issue issue now that we have a better understanding of what is going on.

**Comment by jakirkham** [comment]
Have moved the Cython coverage problem into issue ( https://github.com/jakirkham/cyminmax/issues/13 ).
